### PR TITLE
Update README.md file

### PR DESCRIPTION
**Pull request by gautam-dev-maker**
1) Update the SRA Board image
2) Add image of Wall-E bot with OLED
3) Update Git repo link since the name of repo was changed

### CODE REVIEW

**Comment by gautam-dev-maker** [comment]
The PR looks good to me, @SAtacker could you verify it once

**Comment by SAtacker** [comment]
Could you also do a cleanup of https://github.com/SRA-VJTI/Wall-E/tree/readme_update/windows_instructions likewise https://github.com/Jamm02/Wall-E/tree/readme_update/windows_instructions?

**Comment by gautam-dev-maker** [comment]
@SAtacker This [PR](https://github.com/SRA-VJTI/Wall-E/pull/98) already solves it and add extra instructions for better installation.

**Comment by SAtacker** [comment]
> @SAtacker This [PR](https://github.com/SRA-VJTI/Wall-E/pull/98) already solves it and add extra instructions for better installation.

Yup, got it.

**Comment by SAtacker** [comment]
LGTM

**Review by SAtacker — APPROVED** [review]

**Pull request merged**
